/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const StripeConfig = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [Cart], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [Cart], []),
  'setProductActive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setStripeConfig' : IDL.Func([StripeConfig], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [Cart], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const StripeConfig = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [Cart], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [Cart], []),
    'setProductActive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setStripeConfig' : IDL.Func([StripeConfig], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [Cart], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
  });
};

export const init = ({ IDL }) => { return []; };