/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'priceInCents' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'priceInCents' : bigint,
}
export interface StripeConfig {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], Cart>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<[string, string], string>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listCategories' : ActorMethod<[], Array<string>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'removeFromCart' : ActorMethod<[bigint], Cart>,
  'setProductActive' : ActorMethod<[bigint, boolean], boolean>,
  'setStripeConfig' : ActorMethod<[StripeConfig], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItem' : ActorMethod<[bigint, bigint], Cart>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];